name: Build and Publish Github regisrty
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@master
    - name: Install Docker
      run: curl -sSL https://get.docker.com/ | sh
    - name: Login to Github Registry
      run: echo ${{ secrets.REGISTRY_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Build the tagged PHP image
      run: docker build . --file Dockerfile --target=php -t docker.pgk.github.com/${{ github.repository }}/php
    - name: Build the tagged NGINX image
      run: docker build . --file Dockerfile --target=nginx -t docker.pgk.github.com/${{ github.repository }}/nginx
    - name: Publish images to Github Registry
      run: |
        PHP_ID=docker.pgk.github.com/${{ github.repository }}/php
        NGINX_ID=docker.pgk.github.com/${{ github.repository }}/nginx
        VERSION=$(echo ${GITHUB_REF:10})
        echo ${GITHUB_REF:10}
        docker tag $PHP_ID:$VERSION
        docker push $PHP_ID:$VERSION
        docker tag $NGINX_ID:$VERSION
        docker push $NGINX_ID:$VERSION
    - name: Publish the latest image to Github Registry
      run: |
        docker tag docker.pgk.github.com/${{ github.repository }}/php:latest
        docker push docker.pgk.github.com/${{ github.repository }}/php:latest
        docker tag docker.pgk.github.com/${{ github.repository }}/nginx:latest
        docker push docker.pgk.github.com/${{ github.repository }}/nginx:latest
