name: Build and Publish Github regisrty
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@master
    - name: Install Docker
      run: curl -sSL https://get.docker.com/ | sh
    - name: Login to Github Registry
      run: echo ${{ secrets.REGISTRY_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged PHP image
      run: docker build . --file Dockerfile --target=php -t docker.pkg.github.com/${{ github.repository }}/php:${{steps.vars.outputs.tag}}
    - name: Build the tagged NGINX image
      run: docker build . --file Dockerfile --target=nginx -t docker.pkg.github.com/${{ github.repository }}/nginx:${{steps.vars.outputs.tag}}
    - name: Build the latest PHP image
      run: docker build . --file Dockerfile --target=php -t docker.pkg.github.com/${{ github.repository }}/php:latest
    - name: Build the latest NGINX image
      run: docker build . --file Dockerfile --target=nginx -t docker.pkg.github.com/${{ github.repository }}/nginx:latest
    - name: Publish images to Github Registry
      run: |
        docker push docker.pkg.github.com/${{ github.repository }}/php:${{steps.vars.outputs.tag}}
        docker push docker.pkg.github.com/${{ github.repository }}/nginx:${{steps.vars.outputs.tag}}
    - name: Publish the latest image to Github Registry
      run: |
        docker push docker.pkg.github.com/${{ github.repository }}/php:latest
        docker push docker.pkg.github.com/${{ github.repository }}/nginx:latest
