name: Build and Publish Github regisrty
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@master
    - name: Install Docker
      run: curl -sSL https://get.docker.com/ | sh
    - name: Login to Github Registry
      run: echo ${{ secrets.REGISTRY_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged PHP Docker image
      run: docker build --target=php -t docker.pgk.github.com/${{ github.repository }}/php:$
    - name: Build the tagged NGINX Docker image
      run: docker build --target=nginx -t docker.pgk.github.com/${{ github.repository }}/nginx:$
    - name: Build the latest PHP Docker image
      run: docker build --target=php -t docker.pgk.github.com/${{ github.repository }}/php:latest
    - name: Build the latest NGINX Docker image
      run: docker build --target=nginx -t docker.pgk.github.com/${{ github.repository }}/nginx:latest
    - name: Publish the tagged image to Docker Repository
      run: |
        docker push docker.pgk.github.com/${{ github.repository }}/php:$
        docker push docker.pgk.github.com/${{ github.repository }}/nginx:$
    - name: Publish the tagged image to Docker Repository
      run: |
        docker push docker.pgk.github.com/${{ github.repository }}/php:latest
        docker push docker.pgk.github.com/${{ github.repository }}/nginx:latest
