name: Workflow for test my app
on: push

jobs:
  dependencies:
    name: Install Php dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Cache Composer
      id: cache-composer
      uses: actions/cache@v1
      with: 
        path: vendor/
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
    - name:  Install dependencies
      if: steps.cache-composer.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest --no-scripts
  
  test-unit:
    name: Test Unit
    runs-on: ubuntu-latest  
    needs: dependencies  
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Cache Composer
      id: cache-composer
      uses: actions/cache@v1
      with:
        path: vendor/
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
    - name: Run Test Unit  
      run: bin/phpunit tests/Unit

  test-integration:
    name: Test Intégration
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Cache Composer
      id: cache-composer
      uses: actions/cache@v1
      with:
        path: vendor/
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
    - name: Run Test Integration
      run: bin/phpunit tests/Integration

  test-functionnal:
    name: Test Functional
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
    - name: Checkout srouce code
      uses: actions/checkout@v2
    - name: Cache Composer
      id: cache-composer
      uses: actions/cache@v1
      with:
        path: vendor/
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
    - name: Run Test Functional
      run: php vendor/bin/behat
